config/routes.rb
Rails.application.routes.draw do

  devise_for :owners
  devise_for :costumers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :places
	root 'places#index'
	resources :places do
    collection do
      get :mine
    end
		resources :comments, only: [:create, :destroy]
    resources :reservs, only: [:create, :destroy]
	end

	resources :categories, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :places
end

app/models/comment.rb
class Comment < ApplicationRecord
  #validates :body, length { minimum: 15 }
  belongs_to :place
  belongs_to :costumer
end

app/models/costumer.rb
class Costumer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments, dependent: :destroy
  has_many :reservs, dependent: :destroy

  #before_destroy :assign
end

app/models/food.rb
class Food < ApplicationRecord
  has_and_belongs_to_many :places
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places, dependent: :destroy
end

app/models/place.rb
class Place < ApplicationRecord
	validates :name, presence: true
	validates :adress, length: { maximum: 50 }
	validates :phone_number, length: { minimum: 10 }, uniqueness: true
	validates :contact_mail, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, message: "not an e-mail adress" }, uniqueness: true
	validate :check_established_at

	has_many :comments, dependent: :destroy
	has_many :reservs, dependent: :destroy
	has_many :costumers, through: :reservs
	has_and_belongs_to_many :foods
	has_one :social_profile

	belongs_to :category
	belongs_to :owner

	accepts_nested_attributes_for :social_profile

	def check_established_at
		if established_at.present? && established_at > Date.today
			errors.add(:established_at, "Couldn't be feature")
		end
	end

	# def category
	# 	Category.find(category_id)
	# end
end

app/models/reserv.rb
class Reserv < ApplicationRecord
  validate :check_date
  #validates :costumer_id, uniqueness: { scope: :place_id }  #bir kişinin sadece 1 resrvasyon yapmasını sağlıyor...


  belongs_to :place
  belongs_to :costumer

  def check_date
		if date.present? && date < Date.today
			errors.add(:established_at, "Couldn't be past")
		end
	end

end

app/models/social_profile.rb
class SocialProfile < ApplicationRecord
  belongs_to :place, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all
  end

  def show
  	@category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_costumer!
  before_action :set_place
  before_action :set_comment, only: [:destroy]
  before_action :authorize_costumer!, only: [:destroy]


  def create
    @comment = @place.comments.create(comment_params)
    @comment.costumer = current_costumer
    if @comment.save
      flash[:success] = 'Comment saved successfuly'
    end
    redirect_to place_path(@place)
  end

  def destroy
    @comment.destroy
    redirect_to @place, notice: 'Comment was deleted.'
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
    
    def set_place
      @place = Place.find(params[:place_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def authorize_costumer!
      redirect_to @place, notice: 'Not authorized.' unless @comment.costumer_id == current_costumer.id
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :set_place, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_owner!, except: [:index, :show]
	before_action :authorize_owner!, only: [:edit, :update, :destroy]
	#before_action :authenticate_costumer!, except: [:index, :show]

	def new
		@place = Place.new
		@place.build_social_profile
		load_form_data
	end

	def  index
		@places = Place.all
	end

	def show
	end

	def create
		@place = current_owner.places.new(place_params)

		if @place.save
			flash[:success] = 'Place infos saved successfuly'
			redirect_to place_path(@place)
		else
			load_form_data
			render :new
		end
	end

	def edit
		load_form_data
	end

	def update


		if @place.update(place_params)
			flash[:success] = 'Place infos updated successfuly'
			redirect_to place_path(@place)
		else
			load_form_data
			render :edit
		end

	end

	def destroy

		@place.destroy
		flash[:warning] = 'Place infos deleted successfuly'
		redirect_to places_path
	end

	def mine
		@places = current_owner.places
	end

	private
		def authorize_owner!
			redirect_to root_path, notice: 'Not authorized...' unless @place.owner_id == current_owner.id
		end

		def set_place
			@place = Place.find(params[:id])
		end

		def place_params
			params.require(:place).permit(:name, :adress, :phone_number, :city, :description,
											:contact_mail, :established_at, :category_id, food_ids: [],
											social_profile_attributes: [:facebook, :twitter, :instagram, :foursquare]
											)
		end

		def load_form_data
			@categories = Category.all.collect { |c| [c.name, c.id] }
			@foods = Food.all
		end
end

app/controllers/reservs_controller.rb
class ReservsController < ApplicationController
  before_action :authenticate_costumer!
  before_action :set_place
  before_action :set_reserv, only: [:destroy]

  def create
    @reserv = @place.reservs.build(reserv_params)
    @reserv.costumer_id = current_costumer.id

    if @reserv.save
      redirect_to @place, notice: 'Reservation has been made.'
    else
      redirect_to @place, notice: 'Reservation could not save'
    end

  end

  def destroy
    @reserv.destroy
    redirect_to @place, notice: 'Reservation was deleted.'
  end

  private

    def set_reserv
      @reserv = Reserv.find(params[:id])
    end

    def set_place
      @place = Place.find(params[:place_id])
    end

    def reserv_params
      params.require(:reserv).permit(:number_of_p, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/reservs_helper.rb
module ReservsHelper
end

app/views/categories/_flash.html.erb
<% if !flash.empty? %>
  <div id="flash">
    <% flash.keys.each do |k| %>
      <div class="<%= k %>">
        <%= flash[k] %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>
<p>
	<% @categories.each do |c| %>
		<b><i><%= link_to c.name, category_path(c) %></i></b><br><br>
	<% end %>
</p>

app/views/categories/show.html.erb
<h1> <%= @category.name %> </h1>

	<% @category.places.each do |p| %>
		<p><b>Name : </b><i><a href="<%= place_path(p) %>"> <%= p.name %> </a></i><br>
		<b>Adress : </b><%= p.adress %><br>
		<b>Desc : </b><%= p.description %><br>
		<b>Phone Number : </b><u><%= p.phone_number %></u><br>
		<b>City : </b><%= p.city  %><br>
		<hr></p>
	<% end %>

app/views/comments/_comment_list.html.erb
  <% @place.comments.each do |comment| %>
    <p><b> Comment by
    <small><%= comment.costumer.email %> : </small></b><br>
    <%= comment.body %>
    <% if current_costumer.present? && comment.costumer_id = current_costumer.id %>
      <i><%= link_to 'Delete comment', place_comment_path(@place, comment), method: :delete, data: { confirm:  'Do you want to delete...' } %></i>
    <% end %>
    <br></p>
  <% end %>

app/views/comments/_form.html.erb
<%= form_for ([@place, @place.comments.build]) do |f| %>
  <%= f.label :body %><br>
  <%= f.text_area :body, placeholder: 'Write your comment here', rows: 5%><br>

  <%= f.submit 'SUBMIT' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    .center {
      margin: auto;
      width: 60%;
      border: 3px;
      padding: 10px;
    }
    </style>
  </head>

  <body>
  <div class="center">
    <% if !flash.empty? %>
      <div id="flash">
        <% flash.keys.each do |k| %>
          <div class="<%= k %>">
            <%= flash[k] %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="center">
    <% if current_costumer.present? %>
      <%= current_costumer.email %>
      <%= link_to 'Logout', destroy_costumer_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Login as a Customer', new_costumer_session_path %>
      <%= link_to 'Sign Up as a Customer', new_costumer_registration_path %>
    <% end %>
    <% if current_owner.present? %>
      <%= current_owner.email %>
      <%= link_to 'My Places', mine_places_path %>
      <%= link_to 'Logout', destroy_owner_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Login as an Owner', new_owner_session_path %>
      <%= link_to 'Sign Up as an Owner', new_owner_registration_path %>
    <% end %>
  </div>


  <div class="center">
      <%= yield %>
      <br><i><%= link_to 'Add new place', new_place_path %></i>
      <i><%= link_to 'List Categories', categories_path %></i>
      <i><%= link_to 'List places', root_path %></i>
  </div>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name, placeholder: 'name' %><br>

	<%= f.label :adress %><br>
	<%= f.text_field :adress, placeholder: 'adress' %><br>

	<%= f.label :phone_number %><br>
	<%= f.text_field :phone_number, placeholder: 'phone_number' %><br>

	<%= f.label :city %><br>
	<%= f.text_field :city, placeholder: 'city' %><br>

	<%= f.label :description %><br>
	<%= f.text_area :description, placeholder: 'description', rows: 5%><br>

	<%= f.label :contact_mail %><br>
	<%= f.text_field :contact_mail, placeholder: 'contact_mail' %><br>

	<%= f.label :established_at %><br>
	<%= f.date_select :established_at, placeholder: 'established_at' %><br>

	<%= f.label :Category %>
	<%= f.select :category_id, @categories %><br>

	<%= f.label :Foods %><br>
	<%= f.collection_check_boxes(:food_ids, @foods, :id, :name) %><br>

	<%= form_for :social_profile do |sf| %>
	<h3> Social Profiles </h3>
		<%= sf.label :facebook %><br>
		<%= sf.text_field :facebook, placeholder: 'facebook' %><br>

		<%= sf.label :twitter %><br>
		<%= sf.text_field :twitter, placeholder: 'twitter' %><br>

		<%= sf.label :instagram %><br>
		<%= sf.text_field :instagram, placeholder: 'instagram' %><br>

		<%= sf.label :foursquare %><br>
		<%= sf.text_field :foursquare, placeholder: 'foursquare' %><br>

	<% end %>

	<%= f.submit 'SUBMIT' %>

<% end %>

<!-- <%= form_tag places_path, method: :post do %>

	<%= text_field_tag 'title' %>
	<%= text_area_tag 'description' %>
	<%= date_field_tag 'planned_to' %>
	<%= submit_tag 'SUBMIT' %>

<% end %> -->

app/views/places/_place_list.html.erb
<h2> Listing your Places </h2>
<% @places.each do |p| %>
  <p> <b>Name : </b><i><a href="<%= place_path(p) %>"> <%= p.name %> </a></i><br>
  <b>Adress : </b><%= p.adress %><br>
  <b>Desc : </b><%= p.description %><br>
  <b>Phone Number : </b><u><%= p.phone_number %></u><br>
  <b>City : </b><%= p.city  %><br>
  <b>Category : </b><%= p.category.name %><br>
  <b>Foods : </b><%= p.foods.collect{|x| x.name}.join(" - ") %><br>
  <b>Facebook : </b><%= p.social_profile.facebook %><br>
  <b>Twitter : </b><%= p.social_profile.twitter %><br>
  <b>Instagram : </b><%= p.social_profile.instagram %><br>
  <b>Foursquare : </b><%= p.social_profile.foursquare %><br>
  <br><i><%= link_to 'Edit place', edit_place_path(p) %></i>
  <i><%= link_to 'Delete place', place_path(p), method: :delete, data: { confirm:  'Do you want to delete...' } %></i>
</p>
<hr>
<% end %>

app/views/places/edit.html.erb
<h2>Editing Place ...</h2>

<% if @place.errors.any?  %>
	<% @place.errors.full_messages.each do |e| %>
		<b><i><%= e %></i></b><br><br>
	<% end %>
<% end %>

<form action="<%= place_path %>" method="post">
	<input type="hidden" name="_method" value="put">

	<%= render 'form' %>

</form>

<br><i><%= link_to 'back', place_path %></i>

app/views/places/index.html.erb
<h2> Listing all Places </h2>
<% @places.each do |p| %>
  <p> <b>Name : </b><i><a href="<%= place_path(p) %>"> <%= p.name %> </a></i><br>
  <b>Adress : </b><%= p.adress %><br>
  <b>Desc : </b><%= p.description %><br>
  <b>Phone Number : </b><u><%= p.phone_number %></u><br>
  <b>City : </b><%= p.city  %><br>
  <b>Category : </b><%= p.category.name %><br>
  <b>Foods : </b><%= p.foods.collect{|x| x.name}.join(" - ") %>
</p>

<hr>
<% end %>

app/views/places/mine.html.erb
<%= render 'place_list' %>

app/views/places/new.html.erb
<h2> Add a new Place...</h2>

<% if @place.errors.any?  %>
	<% @place.errors.full_messages.each do |e| %>
		<b><i><%= e %></i></b><br><br>
	<% end %>
<% end %>



<%= render 'form' %>

app/views/places/show.html.erb
<h3>Showing <%= @place.id %> th Place</h3>
<p> <b>Name : </b><i> <%= @place.name %> </i><br>
<b>Adress : </b><%= @place.adress %><br>
<b>Desc : </b><%= @place.description %><br>
<b>Phone Number : </b><u><%= @place.phone_number %></u><br>
<b>City : </b><%= @place.city %><br>
<b>Category : </b><%= @place.category.name %><br>
<b>Owner : </b><%= @place.owner.email %> <b> id : </b> <%= @place.owner.id %> <br>
<b>Foods : </b><%= @place.foods.collect{|x| x.name}.join(" - ") %><br>
<b>Facebook : </b><%= @place.social_profile.facebook %><br>
<b>Twitter : </b><%= @place.social_profile.twitter %><br>
<b>Instagram : </b><%= @place.social_profile.instagram %><br>
<b>Foursquare : </b><%= @place.social_profile.foursquare %><br>
<% if current_owner.present? && current_owner.id == @place.owner_id %>
  <br><i><%= link_to 'Edit place', edit_place_path %></i>
  <i><%= link_to 'Delete place', place_path(@place), method: :delete, data: { confirm:  'Do you want to delete...' } %></i>
<% end %>
</p>

<%= render 'reservs/reserv_list' %>

<% if current_costumer.present? %>
  <%= render 'reservs/form' %>
<% end %>

<%= render 'comments/comment_list' %>

<% if current_costumer.present? %>
  <%= render 'comments/form' %>
<% end %>

app/views/reservs/_form.html.erb
<%= form_for [@place, @place.reservs.build] do |f| %>
  <h3> Make a reservation </h3>
  <%= f.label :number_of_p %><br>
  <%= f.text_field :number_of_p, placeholder: 'number_of_people' %><br>

  <%= f.label :date %><br>
  <%= f.datetime_select :date %><br>

  <%= f.submit 'SUBMIT' %>

<% end %>

app/views/reservs/_reserv_list.html.erb
<p>
  <% @place.reservs.each do |r| %>
    <h4> Reservations info </h4>
    <b> Reservation made by </b><small><%= r.costumer.email %>  </small><br>
    <b> Reservation Date : </b> <%= r.date %><br>
    <b> Number of Reservation people : </b> <%= r.number_of_p %>
    <% if current_costumer.present? && r.costumer_id = current_costumer.id %>
      <i><%= link_to 'Delete reservation', place_reserv_path(@place, r), method: :delete, data: { confirm:  'Do you want to delete...' } %></i>
    <% end %>
    <hr>
    <br>
  <% end %>
</p>